### ISSUE TITLE
D2 ONLY: Libgcrypt not initialized  - static constructor problem in HmacAuthCode 

### ISSUE THREAD

**Issue by don-clugston-sociomantic** [sociomantic-tsunami/swarm#171] opened 2017-11-14 16:29 UTC
Minimal test case:
```d
module test.main;
import ocean.transition;
import swarm.neo.authentication.HmacAuthCode;

public void main ( istring [] args ) {}
```

Compile with D1 -- ok. 
But if compiled with D2, writes to /var/log/syslog
``test: Libgcrypt warning: missing initialization - please fix the application``

**Comment by gavin-norman-sociomantic** [comment] 2017-11-14 16:32
Huh. Do you know what the cause of this is?

**Comment by don-clugston-sociomantic** [comment] 2017-11-14 16:33
It looks as though the module `shared static this` is not being run. Or not run properly.

**Comment by gavin-norman-sociomantic** [comment] 2017-11-14 16:34
https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/authentication/HmacAuthCode.d#L114-L117

Ohh, weird.

**Comment by don-clugston-sociomantic** [comment] 2017-11-14 16:36
Yeah, exactly. That doesn't work. I don't know why.

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 16:36
Hmm, but that's just when the libgcrypt is used - presumably there's another constructor in the ocean that takes care of the initialisation. Where's that hidden?

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 16:38
https://github.com/sociomantic-tsunami/ocean/blob/aca225006522fd0cb3a436d23fb16b58528a082f/src/ocean/util/cipher/gcrypt/core/Gcrypt.d#L234

**Comment by don-clugston-sociomantic** [comment] 2017-11-14 16:42
BTW you can really get confused if you try to fix this naively. syslog hides duplicate messages, so you can't just rerun it and `tail /var/log/syslog`, it won't show up there unless you cause another error to be written to syslog.

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 17:03
It seems that the initialization function at (https://github.com/sociomantic-tsunami/ocean/blob/aca225006522fd0cb3a436d23fb16b58528a082f/src/ocean/util/cipher/gcrypt/core/Gcrypt.d#L234) is not actually called neither from the D1 or D2 builds (as the HMAC doesn't use Gcrypt wrapper), but for some reason only D2 build makes library emit a syslog line. If you put a `gcry_control(GCRYCTL_INITIALIZATION_FINISHED, 0);` in HMAC constructor this goes away. I'm trying to see why D1 doesn't emit this issue.

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 17:15
From the docs:

```
/* This is our handmade constructor.  It gets called by any function
   likely to be called at startup.  The suggested way for an
   application to make sure that this has been called is by using
   gcry_check_version. */
```

https://github.com/Chronic-Dev/libgcrypt/blob/e5a923dee8ad0539a53f5d16076ff326e4b49fa5/src/global.c#L147

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 17:18
So, this is the module constructor that's being called in D1:

https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/cipher/gcrypt/c/libversion.d#L38

But this constructor is not marked `static shared this` in D2 build, so it's called _after_ `static shared` constructor of the `HmacAuthCode`.

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 17:21
Making https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/cipher/gcrypt/c/libversion.d#L38 `shared static` fixes the things.

**Comment by nemanja-boric-sociomantic** [comment] 2017-11-14 17:35
https://github.com/sociomantic-tsunami/ocean/pull/360 should fix it.

**Comment by gavin-norman-sociomantic** [comment] 2017-11-15 09:17
@don-clugston-sociomantic ocean patch release done. Could you confirm that this fixes the problem you're seeing?

**Comment by don-clugston-sociomantic** [comment] 2017-11-15 09:43
Confirmed that this fixes my test case.

**Comment by gavin-norman-sociomantic** [comment] 2017-11-15 09:44
Excellent! Closing.

**Closed as completed by gavin-norman-sociomantic** 2017-11-15 09:44 UTC
Labels: res-invalid
